### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by jottinger** [ChasTechProjects/Debian64Pi#4]
It's worth noting that the default user/password for the image is "debian/debian" - not hard to figure out but it'd be nice to be explicit. Will file a PR when I get time, and IF I get time.

**Comment by TwinUsers** [comment]
It’s also listed in the README 👍

**Comment by jottinger** [comment]
Dadgummit all to heck, you're right - I just MISSED IT like a noob. Sorry about that. Consider the request retracted. Thank you.
