### ISSUE TITLE
Poor performance when compare to other 32/64 bit OS

### ISSUE THREAD

**Issue by undergroundSimplex** [ChasTechProjects/Debian64Pi#8]
I bench-marked your 64-bit Debian release (10th January 2020), 32-bit official raspbian OS and 64-bit Ubuntu Pi Server. However, I find that my computationally expensive program takes 2.5x longer time to complete on 64-bit Debian. I wonder what makes such difference.

**Comment by TwinUsers** [comment]
Try installing cpufrequtils and do the test again.

**Comment by undergroundSimplex** [comment]
Great thanks. They have similar peformance after I run `cpufreq-set -r -g powersave/performance`
